version: '2'
 
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - ./'C:\Vignesh\Docker\kafka\zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '29092:29092'
      - '9092:9092' 
    volumes:
      - ./'C:\Vignesh\Docker\kafka\kafka_data:/bitnami'
      - ./'C:\Vignesh\Docker\kafka\kafka_log:/tmp/kafka_mounts/logs'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_DIRS=/tmp/kafka_mounts/logs
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
     
    depends_on:
      - zookeeper
  kafka-connect:
    image: 'bitnami/kafka:latest'
    container_name: kafka_connect
    ports:
      - '8083:8083'
    volumes:
      - ./'C:\Vignesh\Docker\kafka\kafka_connect_data:/bitnami'
     ## - '/Users/vigenshm/Docker/kafka/kafka_connect_config/connect-distributed.properties:/opt/bitnami/kafka/config/connect-distributed.properties'
    depends_on:
      - zookeeper
      - kafka
    command: /opt/bitnami/kafka/bin/connect-distributed.sh /opt/bitnami/kafka/config/connect-distributed.properties
 
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=local
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://kafka_connect:8083
    depends_on:
      - zookeeper
      - kafka